export const VERSION = '3';
export const TYPE = 'AlexaInterface';

export const NAMESPACES = {
  Alexa: 'Alexa',
  Authorization: 'Alexa.Authorization',
  ContactSensor: 'Alexa.ContactSensor',
  Cooking: 'Alexa.Cooking',
  Discovery: 'Alexa.Discovery',
  MotionSensor: 'Alexa.MotionSensor',
  Speaker: 'Alexa.Speaker',
  StepSpeaker: 'Alexa.StepSpeaker',
  LockController: 'Alexa.LockController',
  InputController: 'Alexa.InputController',
  ColorController: 'Alexa.ColorController',
  PowerController: 'Alexa.PowerController',
  TemperatureSensor: 'Alexa.TemperatureSensor',
  ChannelController: 'Alexa.ChannelController',
  TimeController: 'Alexa.Cooking.TimeController',
  TimeHoldController: 'Alexa.TimeHoldController',
  PlaybackController: 'Alexa.PlaybackController',
  ThermostatController: 'Alexa.ThermostatController',
  PowerLevelController: 'Alexa.PowerLevelController',
  PresetController: 'Alexa.Cooking.PresetController',
  BrightnessController: 'Alexa.BrightnessController',
  PercentageController: 'Alexa.PercentageController',
  CameraStreamController: 'Alexa.CameraStreamController',
  ColorTemperatureController: 'Alexa.ColorTemperatureController',
  EndpointHealth: 'Alexa.EndpointHealth',
};

export const NAMES = {
  AcceptGrant: 'AcceptGrant',
  AcceptGrantResponse: 'AcceptGrant.Response',
  DiscoveryResponse: 'Discover.Response',
  Response: 'Response',
  Discover: 'Discover',
  ErrorResponse: 'ErrorResponse',
  SetColor: 'SetColor',
  ReportState: 'ReportState',
  StateReport: 'StateReport',
  SetBrightness: 'SetBrightness',
  AdjustBrightness: 'AdjustBrightness',
  TurnOn: 'TurnOn',
  TurnOff: 'TurnOff',
  SetColorTemperature: 'SetColorTemperature',
  DecreaseColorTemperature: 'DecreaseColorTemperature',
  IncreaseColorTemperature: 'IncreaseColorTemperature',
  ResumeSchedule: 'ResumeSchedule',
  SetThermostatMode: 'SetThermostatMode',
  SetTargetTemperature: 'SetTargetTemperature',
  AdjustTargetTemperature: 'AdjustTargetTemperature',
  ChangeReport: 'ChangeReport',
};
